version: '3'

services:
  sched:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    container_name: sched
    depends_on:
      - redis
    restart: always
    environment:
      - REDIS_URI=redis:6379
      - REDIS_DB=task-scheduler
      - REDIS_PASSWORD=
    ports:
      - 8443:8443
    links:
      - redis

  redis: 
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local